name: Test on Multiple OS

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: packages/insomnia

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # Operating systems to test
        node-version: [20]                      # Node.js versions to test
        attempt: [1, 2]         # Repeat tests 10 times

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install js-sanitizer
        run: npm i --save-dev git+https://github.com/Negar-Hashemi/js-sanitizer.git

      - name: Testing on OS (${{ matrix.os }}) with Node.js (version ${{ matrix.node-version }}) attempt ${{ matrix.attempt }}
        run: |
          echo "Run attempt: ${{ matrix.attempt }}"
          npm run test
    continue-on-error: false
